# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160119_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('secret', models.CharField(max_length=32)),
                ('providers', models.ManyToManyField(to='app.FoodProvider')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='app.FoodProvider'),
        ),
    ]
