# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160226_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrequest',
            name='providers',
            field=models.ManyToManyField(blank=True, to='app.FoodProvider'),
        ),
    ]
