# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160226_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrequest',
            name='all_providers',
            field=models.BooleanField(default=False),
        ),
    ]
