# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160227_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedentry',
            name='user',
        ),
    ]
