# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_feedentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='open',
            field=models.BooleanField(default=True, verbose_name=b'Open for ordering'),
        ),
    ]
