# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160228_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrequest',
            name='deliveries',
            field=models.BooleanField(default=True),
        ),
    ]
