# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notificationrequest_deliveries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrequest',
            name='deliveries',
            field=models.BooleanField(default=False),
        ),
    ]
