# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_menuimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='silent',
            field=models.BooleanField(default=False, help_text=b"Don't send notifications for this order"),
        ),
    ]
