# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_silent'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodprovider',
            name='logo',
            field=models.ImageField(null=True, upload_to=b'logos'),
        ),
        migrations.AddField(
            model_name='foodprovider',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
