# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160423_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False, help_text=b"Food won't be delivered for this order"),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_reason',
            field=models.TextField(blank=True, help_text=b'Reason for cancelling this order', null=True),
        ),
    ]
