# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20160425_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('secret', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
        ),
    ]
