# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20160426_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvite',
            name='used_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
