# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20160426_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodprovider',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(blank=True, help_text=b'Can be picked at random as soon a users have placed an order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='open',
            field=models.BooleanField(default=True, help_text=b'', verbose_name=b'Open for ordering'),
        ),
    ]
