# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-19 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_auto_20160428_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.BooleanField(default=True, help_text=b'', verbose_name=b'Open for joining')),
                ('closing_time', models.DateTimeField(help_text=b'Closing time for joining the group')),
                ('departing_time', models.DateTimeField(help_text=b'Time leaving the office')),
                ('silent', models.BooleanField(default=False, help_text=b"Don't send notifications for this order")),
                ('notes', models.TextField(blank=True, default=b'')),
                ('cancelled', models.BooleanField(default=False, help_text=b"Food won't be delivered for this order")),
                ('cancelled_reason', models.TextField(blank=True, help_text=b'Reason for cancelling this order', null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EatingGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_drive', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('eating_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EatingGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='foodprovider',
            name='type',
            field=models.TextField(choices=[(b'Takeaway', b'takeaway'), (b'Restaurant', b'restaurant'), (b'Shop', b'shop')], default='restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodprovider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'logos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(blank=True, help_text=b'Can be picked at random as soon as users have placed an order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eatinggroup',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FoodProvider', verbose_name=b'Place'),
        ),
    ]
