# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20160519_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatinggroup',
            name='closing_time',
            field=models.DateTimeField(blank=True, help_text=b'Closing time for joining the group', null=True),
        ),
        migrations.AlterField(
            model_name='eatinggroup',
            name='departing_time',
            field=models.DateTimeField(blank=True, help_text=b'Time leaving the office', null=True),
        ),
    ]
