# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160519_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodprovider',
            name='type',
            field=models.CharField(choices=[(b'Takeaway', b'takeaway'), (b'Restaurant', b'restaurant'), (b'Shop', b'shop')], max_length=50),
        ),
    ]
