# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_eatinggroup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatinggroup',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eatinggroup',
            name='cancelled_reason',
            field=models.TextField(blank=True, help_text=b'Reason for cancelling this outing', null=True),
        ),
        migrations.AlterField(
            model_name='eatinggroup',
            name='closing_time',
            field=models.DateTimeField(blank=True, help_text=b'Closing time for joining the outing', null=True),
        ),
        migrations.AlterField(
            model_name='eatinggroup',
            name='silent',
            field=models.BooleanField(default=False, help_text=b"Don't send notifications for this outing"),
        ),
        migrations.AlterField(
            model_name='eatinggroupmember',
            name='can_drive',
            field=models.BooleanField(default=False, help_text=b'I can drive and have a car.'),
        ),
    ]
