# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20160523_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
