# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20160524_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrequest',
            name='all_outings',
            field=models.BooleanField(default=False),
        ),
    ]
