# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20160525_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='favorites',
            field=models.ManyToManyField(to='app.FoodProvider'),
        ),
    ]
