# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-22 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_company_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='eatinggroup',
            name='departing_time',
            field=models.DateTimeField(help_text=b'Time leaving the office', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(null=True),
        ),
    ]
